image: eicweb.phy.anl.gov:4567/containers/eic_container/eic:latest

default:
  artifacts:
    paths:
      - build/

stages:
  #  - build
  - docker_build
  - docker_push
  - run

docker_image:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_build
  tags:
    - silicon
  script:
    - cd containers/docker 
    - make build-nc

docker_image_push:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_push
  tags:
    - silicon
  script:
    - cd containers/docker 
    - make push

docker_tag:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_build
  tags:
    - silicon
  only:
    - tags
  script:
    - cd containers/docker && make release

