image: eicweb.phy.anl.gov:4567/containers/eic_container/eic:latest

default:
  artifacts:
    paths:
      - juggler/

stages:
  - build
  - run

compile:
  stage: build
  tags:
    - sodium
  before_script:
    - pwd &&  ls -lrth
  script:
    - cd /tmp && git clone --depth=1 https://eicweb.phy.anl.gov/EIC/NPDet.git && mkdir build && cd build && cmake ../NPDet/. && make -j20 install
    - cd $CI_BUILDS_DIR && ls -lrth && mkdir build && cd build && cmake .. && make
    #- git clone https://juggler-ci:_Pgt8fx-X2bnxgdu_8n_@eicweb.phy.anl.gov/EIC/juggler.git juggler

run_example:
  stage: run
  tags:
    - sodium
  script:
    - ./juggler/build/run gaudirun.py juggler/Examples/options/hello_world.py
