image: eicweb.phy.anl.gov:4567/containers/eic_container/eic:latest

#default:
#  artifacts:
#    paths:
#      - build/

stages:
  - build
  - docker_build
  - docker_push
  - deploy
 
compile:
  stage: build
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - silicon
  script:
    - export homedir=$(pwd) &&  pwd && cd /tmp && git clone --depth=1 https://eicweb.phy.anl.gov/EIC/NPDet.git && mkdir build && cd build && cmake ../NPDet/. && make -j20 install
    - cd /tmp && git clone --depth=1 https://eicweb.phy.anl.gov/EIC/eicd.git && mkdir eicd_build && cd eicd_build && cmake ../eicd/. && make -j20 install
    - cd $homedir && ls -lrth && mkdir build && cd build && cmake .. && make -j10

docker:build:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - when: on_success
  tags:
    - silicon
  script:
    - cd containers/docker 
    - make build-nc

docker:push:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_push
  needs: ["docker:build"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - when: on_success
  tags:
    - silicon
  script:
    - cd containers/docker 
    - make push

docker:release:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_build
  rules:
    - if: '$CI_COMMIT_TAG'
  tags:
    - silicon
  script:
    - cd containers/docker && make release

docker:singularity:
  image: eicweb.phy.anl.gov:4567/containers/image_recipes/ubuntu_dind:latest
  stage: docker_push
  needs: ["docker:build"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - when: on_success
  tags: 
    - silicon
  script:
    - cp containers/singularity/juggler.def .
    - /bin/bash .gitlabci/setup.sh
    - /bin/bash .gitlabci/build.sh juggler.def
    - mkdir -p build 
    - cp juggler.sif build/.
    - cp juggler.def build/.
  artifacts:
      expire_in: 90 days 
      paths:
        - build/juggler.sif
        - build/juggler.def

benchmarks:reconstruction:
  stage: deploy
  trigger:
    project: EIC/benchmarks/reconstruction_benchmarks
  needs: ["docker:push"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - when: on_success
  
benchmarks:physics:
  stage: deploy
  trigger:
    project: EIC/benchmarks/physics_benchmarks
  needs: ["docker:push"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master"'
      when: never
    - when: on_success
